### ISSUE TITLE
Could you please upgrade the r2d2-oracle version to adopt the latest rust-oracle?

### ISSUE THREAD

**Issue by zhaopinglu** [rursprung/r2d2-oracle#14]
Could you please upgrade the r2d2-oracle to adopt the latest rust-oracle? Thanks.

**Comment by rursprung** [comment]
this is similar to #6: the library defines a dependency to `oracle 0.5` - with semver this means that you can use any `0.5` version, including `0.5.3` (which is the latest at this point). since this is a library it also doesn't have a `cargo.lock`. so when you run `cargo update` on your project it'll pull in the latest version of `oracle` (and any other dependency; check the cargo handbook on how you can manage this in a more fine-grained way if you need to only update `oracle` for some reason).

=> there's currently nothing to be done here, the library is compatible with the latest minor releases of both dependencies.
